/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';

export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "miro-page":            "var(--c-page)",
        "miro-bg":              "var(--c-bg)",
        "miro-card":            "var(--c-card)",
        "miro-sidebar":         "var(--c-sidebar)",
        "miro-surface-low":     "var(--c-surface-low)",
        "miro-surface":         "var(--c-surface)",
        "miro-surface-high":    "var(--c-surface-high)",
        "miro-surface-highest": "var(--c-surface-highest)",
        "miro-border":          "var(--c-border)",
        "miro-ring":            "var(--c-ring)",
        "miro-scrim":           "var(--c-scrim)",
        "miro-text":            "var(--c-text)",
        "miro-text-secondary":  "var(--c-text-secondary)",
        "miro-placeholder":     "var(--c-placeholder)",
        "miro-blue":            "var(--c-blue)",
        "miro-blue-pressed":    "var(--c-blue-pressed)",
        "miro-blue-light":      "var(--c-blue-light)",
        "miro-violet":          "var(--c-violet)",
        "miro-violet-light":    "var(--c-violet-light)",
        "miro-green":           "var(--c-green)",
        "miro-green-light":     "var(--c-green-light)",
        "miro-teal":            "var(--c-teal)",
        "miro-teal-light":      "var(--c-teal-light)",
        "miro-coral":           "var(--c-coral)",
        "miro-coral-light":     "var(--c-coral-light)",
        "miro-amber":           "var(--c-amber)",
        "miro-amber-light":     "var(--c-amber-light)",
        "miro-orange-light":    "var(--c-orange-light)",
        "miro-pink-light":      "var(--c-pink-light)",
        "miro-red":             "var(--c-red)",
        "miro-red-light":       "var(--c-red-light)",
      },
      fontFamily: {
        sans: [
          "Inter",
          "PingFang SC",
          "Microsoft YaHei",
          "Segoe UI",
          "system-ui",
          "sans-serif",
        ],
        display: [
          "Inter",
          "PingFang SC",
          "Microsoft YaHei",
          "Segoe UI",
          "system-ui",
          "sans-serif",
        ],
        body: [
          "Inter",
          "PingFang SC",
          "Microsoft YaHei",
          "Segoe UI",
          "system-ui",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "Fira Code", "Consolas", "monospace"],
      },
      boxShadow: {
        ring:  "var(--c-shadow-ring)",
        panel: "var(--c-shadow-panel)",
        float: "var(--c-shadow-float)",
        focus: "var(--c-shadow-focus)",
      },
      borderRadius: {
        DEFAULT: "14px",
        panel: "20px",
        shell: "28px",
      },
      backdropBlur: {
        chrome: "24px",
      },
    },
  },
  plugins: [forms],
};
