-- Migration 0004: Add title_source to conversations
-- Tracks how the conversation title was set:
--   'DEFAULT'       — system-assigned (empty or "New Conversation")
--   'AI_GENERATED'  — auto-generated by helper AI model
--   'USER_SET'      — manually renamed by the user
-- This prevents AI from overwriting user-set titles.

ALTER TABLE conversations ADD COLUMN title_source TEXT NOT NULL DEFAULT 'DEFAULT';
